services:
  speakerman:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: speakerman-api-gpu
    runtime: nvidia          # requires NVIDIA Container Toolkit
    environment:
      - NVIDIA_VISIBLE_DEVICES=0   # 0 – использовать первую A5000; поменяйте на 1 для второй
      - WORKERS=4                  # оптимально для A5000, чтобы не переполнить GPU
      - UVICORN_TIMEOUT=120        # таймаут keep-alive (сек)
      - PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:128
    ports:
      - "8000:8000"
    volumes:
      - /mnt/ssd/huggingface_cache:/root/.cache/huggingface 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: "4"
          memory: 8G 